### ISSUE TITLE
Creating a cluster, [PANIC RECOVER] is occurred.

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/cb-ladybug#9]
클러스터 생성 도 중 중단한 적이 있어서 그런지 모르겠지만, 아래와 같이 클러스터 생성할 때 패닉이 발생합니다.(관련 로그 참조)
모든 자원 삭제 후 다시 시도할 예정입니다만 원인 분석이 필요해 보입니다.

* 실행 명령
```
$ ./init.sh AWS
$ ./cluster-create.sh AWS cb-cluster t2.medium 1
$ ./cluster-delete.sh AWS cb-cluster
```

* 관련 로그
```
cb-ladybug                   | 2020/10/27 04:56:14.853205 WARN RESTY Using Basic Auth in HTTP mode is not secure, use HTTPS
cb-ladybug                   | start create vpc (name=cb-cluster-vpc)
cb-ladybug                   | 2020/10/27 04:56:14.869633 WARN RESTY Using Basic Auth in HTTP mode is not secure, use HTTPS
cb-ladybug                   | 2020/10/27 04:56:14.872923 WARN RESTY Using Basic Auth in HTTP mode is not secure, use HTTPS
cb-ladybug                   | 2020/10/27 04:56:16.235128 WARN RESTY Using Basic Auth in HTTP mode is not secure, use HTTPS
cb-ladybug                   | create vpc OK.. (name=cb-cluster-vpc)
cb-ladybug                   | start create firewall (name=cb-cluster-allow-external)
cb-ladybug                   | 2020/10/27 04:56:16.244341 WARN RESTY Using Basic Auth in HTTP mode is not secure, use HTTPS
cb-ladybug                   | {"connectionName":"cb-aws-config","cspSecurityGroupId":"sg-046b9a9dd62415b50","cspSecurityGroupName":"cb-cluster-allow-external","description":"","firewallRules":[{"direction":"inbound","fromPort":"1","ipProtocol":"udp","toPort":"65535"},{"direction":"inbound","fromPort":"1","ipProtocol":"tcp","toPort":"65535"},{"direction":"inbound","fromPort":"-1","ipProtocol":"icmp","toPort":"-1"},{"direction":"outbound","fromPort":"","ipProtocol":"-1","toPort":""}],"id":"cb-cluster-allow-external","keyValueList":[{"Key":"GroupName","Value":"cb-cluster-vpc-delimiter-cb-cluster-allow-external"},{"Key":"VpcID","Value":"vpc-020211c4acc9b48fa"},{"Key":"OwnerID","Value":"635484366616"},{"Key":"Description","Value":"cb-cluster-vpc-delimiter-cb-cluster-allow-external"}],"name":"cb-cluster-allow-external","vNetId":"cb-cluster-vpc"}
cb-ladybug                   | create firewall OK.. (name=cb-cluster-allow-external)
cb-ladybug                   | start create ssh key (name=cb-cluster-sshkey)
cb-ladybug                   | 2020/10/27 04:56:17.386726 WARN RESTY Using Basic Auth in HTTP mode is not secure, use HTTPS
cb-ladybug                   | 2020/10/27 04:56:17.396895 WARN RESTY Using Basic Auth in HTTP mode is not secure, use HTTPS
cb-ladybug                   | 2020/10/27 04:56:17.831667 WARN RESTY Using Basic Auth in HTTP mode is not secure, use HTTPS
cb-ladybug                   | create ssh key OK.. (name=cb-cluster-sshkey)
cb-ladybug                   | start create image (name=cb-aws-config-Ubuntu1804)
cb-ladybug                   | 2020/10/27 04:56:17.838698 WARN RESTY Using Basic Auth in HTTP mode is not secure, use HTTPS
cb-ladybug                   | create image OK.. (name=cb-aws-config-Ubuntu1804)
cb-ladybug                   | start create control plane spec (name=cb-cluster-spec)
cb-ladybug                   | 2020/10/27 04:56:17.849151 WARN RESTY Using Basic Auth in HTTP mode is not secure, use HTTPS
cb-ladybug                   | 2020/10/27 04:56:17.853865 WARN RESTY Using Basic Auth in HTTP mode is not secure, use HTTPS
cb-ladybug                   | create control plane spec OK.. (name=cb-cluster-spec)
cb-ladybug                   | {"time":"2020-10-27T04:56:17.980881481Z","level":"-","prefix":"echo","file":"recover.go","line":"92","message":"[PANIC RECOVER] runtime error: index out of range [0] with length 0 goroutine 60 [running]:\ngithub.com/labstack/echo/v4/middleware.RecoverWithConfig.func1.1.1(0xfa4ba8, 0x1000, 0x0, 0x10a01c0, 0xc00009eb40)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.17/middleware/recover.go:77 +0x105\npanic(0xedd1a0, 0xc00029a1a0)\n\t/usr/local/go/src/runtime/panic.go:969 +0x1b9\ngithub.com/cloud-barista/cb-ladybug/src/rest-api/service.CreateCluster(0xc0002ac9d1, 0x10, 0xc0001c3700, 0xc0002ac9d1, 0x10, 0x8)\n\t/usr/src/app/src/rest-api/service/cluster.go:179 +0x4165\ngithub.com/cloud-barista/cb-ladybug/src/rest-api/router.CreateCluster(0x10a01c0, 0xc00009eb40, 0x9, 0xc0002ac9d1)\n\t/usr/src/app/src/rest-api/router/cluster.go:86 +0x3a8\ngithub.com/cloud-barista/cb-ladybug/src/core/common.NsValidate.func1.1(0x10a01c0, 0xc00009eb40, 0x1, 0x1)\n\t/usr/src/app/src/core/common/ns.go:16 +0x186\ngithub.com/labstack/echo/v4.(*Echo).add.func1(0x10a01c0, 0xc00009eb40, 0xf6b6ad, 0x1b)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.17/echo.go:522 +0x62\ngithub.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1(0x10a01c0, 0xc00009eb40, 0x203000, 0x203000)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.17/middleware/cors.go:121 +0x483\ngithub.com/labstack/echo/v4/middleware.RecoverWithConfig.func1.1(0x10a01c0, 0xc00009eb40, 0x0, 0x0)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.17/middleware/recover.go:98 +0x142\ngithub.com/labstack/echo/v4/middleware.LoggerWithConfig.func2.1(0x10a01c0, 0xc00009eb40, 0x0, 0x0)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.17/middleware/logger.go:117 +0x130\ngithub.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc00000a1e0, 0x108c060, 0xc000168380, 0xc000164500)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.17/echo.go:633 +0x182\nnet/http.serverHandler.ServeHTTP(0xc0001680e0, 0x108c060, 0xc000168380, 0xc000164500)\n\t/usr/local/go/src/net/http/server.go:2843 +0xa3\nnet/http.(*conn).serve(0xc0005405a0, 0x108e460, 0xc0001c3540)\n\t/usr/local/go/src/net/http/server.go:1925 +0x8ad\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:2969 +0x36c\n\ngoroutine 1 [IO wait]:\ninternal/poll.runtime_pollWait(0x7f2ea8c94d58, 0x72, 0x0)\n\t/usr/local/go/src/runtime/netpoll.go:220 +0x55\ninternal/poll.(*pollDesc).wait(0xc000156518, 0x72, 0x0, 0x0, 0xf5a030)\n\t/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45\ninternal/poll.(*pollDesc).waitRead(...)\n\t/usr/local/go/src/internal/poll/fd_poll_runtime.go:92\ninternal/poll.(*FD).Accept(0xc000156500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/usr/local/go/src/internal/poll/fd_unix.go:394 +0x1fc\nnet.(*netFD).accept(0xc000156500, 0x7f2ea8c50ff8, 0x50, 0x50)\n\t/usr/local/go/src/net/fd_unix.go:172 +0x45\nnet.(*TCPListener).accept(0xc00039a260, 0x29e8d60800, 0x0, 0xc000093b10)\n\t/usr/local/go/src/net/tcpsock_posix.go:139 +0x32\nnet.(*TCPListener).AcceptTCP(0xc00039a260, 0x5e94f73da77ae01, 0x0, 0x0)\n\t/usr/local/go/src/net/tcpsock.go:248 +0x65\ngithub.com/labstack/echo/v4.tcpKeepAliveListener.Accept(0xc00039a260, 0xc000093b80, 0x48fa46, 0x5f97a86e, 0x440d2e)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.17/echo.go:875 +0x2f\nnet/http.(*Server).Serve(0xc0001680e0, 0x108a5e0, 0xc00000ef10, 0x0, 0x0)\n\t/usr/local/go/src/net/http/server.go:2937 +0x266\ngithub.com/labstack/echo/v4.(*Echo).StartServer(0xc00000a1e0, 0xc0001680e0, 0x6, 0xf6d9e3)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.17/echo.go:724 +0x385\ngithub.com/labstack/echo/v4.(*Echo).Start(...)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.17/echo.go:644\ngithub.com/cloud-barista/cb-ladybug/src/rest-api.Server()\n\t/usr/src/app/src/rest-api/server.go:41 +0x7e8\nmain.main()\n\t/usr/src/app/src/main.go:25 +0x2a\n\ngoroutine 6 [sleep]:\ntime.Sleep(0x77359400)\n\t/usr/local/go/src/runtime/time.go:188 +0xbf\ngithub.com/cloud-barista/cb-log.levelSetupLoop(0xf5f146, 0xd)\n\t/go/pkg/mod/github.com/cloud-barista/cb-log@v0.1.1/cblogger.go:78 +0x5a\ncreated by github.com/cloud-barista/cb-log.setup\n\t/go/pkg/mod/github.com/cloud-barista/cb-log@v0.1.1/cblogger.go:61 +0xf7\n\ngoroutine 7 [select, 2 minutes]:\ngoogle.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc00011d540)\n\t/go/pkg/mod/google.golang.org/grpc@v1.26.0/balancer_conn_wrappers.go:69 +0xc8\ncrea\n"}
cb-ladybug                   | {"time":"2020-10-27T04:56:17.98194195Z","id":"","remote_ip":"172.19.0.1","host":"localhost:8080","method":"POST","uri":"/ladybug/ns/cb-aws-namespace/clusters","user_agent":"curl/7.58.0","status":500,"error":"","latency":3129793259,"latency_human":"3.129793259s","bytes_in":185,"bytes_out":36}
cb-ladybug                   | start delete MCIS (name=cb-cluster)
cb-ladybug                   | 2020/10/27 04:57:37.927881 WARN RESTY Using Basic Auth in HTTP mode is not secure, use HTTPS
cb-ladybug                   | delete MCIS skip (cannot find).. (name=cb-cluster)
cb-ladybug                   | {"time":"2020-10-27T04:57:37.938121069Z","id":"","remote_ip":"172.19.0.1","host":"localhost:8080","method":"DELETE","uri":"/ladybug/ns/cb-aws-namespace/clusters/cb-cluster","user_agent":"curl/7.58.0","status":200,"error":"","latency":11013851,"latency_human":"11.013851ms","bytes_in":0,"bytes_out":42}
cb-ladybug                   | start delete MCIS (name=cb-cluster)
cb-ladybug                   | 2020/10/27 05:00:00.196767 WARN RESTY Using Basic Auth in HTTP mode is not secure, use HTTPS
```

**Comment by sykim-etri** [comment]
cb-tumblebug의 버그로 인한 것으로 파악되며, cb-tumblebug v0.2.5 사용시 재현되지 않으므로 이슈를 닫습니다.
